site_name: Prophetverse

theme:
  name: material
  logo: static/logo-removebg.png
repo_url: https://github.com/felipeangelimvieira/hierarchical_prophet

nav:
  - Home: index.md
  - Examples:
      - Univariate Time Series: examples/univariate.ipynb
      - Hierarchical Time Series: examples/hierarchical.ipynb
  - Reference:
      - Sktime:
        - Prophet: reference/sktime/prophet.md
        - Hierarchical Prophet: reference/sktime/hierarchical_prophet.md
      - Core:
        - Inference Engine: reference/core/inference_engine.md
      - Exogenous Effects: reference/effects.md
        


plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src] 
  - mkdocs-jupyter:
      use_directory_urls: false

markdown_extensions:
  - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css