site_name: Hierarchical Prophet

theme:
  name: material


nav:
  - Home: index.md
  - Examples:
      - Univariate Time Series: examples/univariate.ipynb
      - Hierarchical Time Series: examples/hierarchical.ipynb
  - Reference:
      - Prophet: reference/prophet.md
      - Hierarchical Prophet: reference/hierarchical_prophet.md


plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src] 
  - mkdocs-jupyter:
      use_directory_urls: false

markdown_extensions:
  - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js